### ISSUE TITLE
I can't unselect all segments

### ISSUE THREAD

**Issue by libarra** [omaralbeik/WeekdaysSegmentedControl#3]
First thank you for create a nice Control!

Well, I have a problem trying to unselect all segments in code.

I try using:

**myControl.daysString = "0000000"**  or  **myControl.selectedIndexes = []**

but nothing happen in execution time.

Please your help, thanks in advance.

Luis.

**Comment by omaralbeik** [comment]
Hey Luis,
Please make sure you're using the latest version.
Here is how you can reset selection
```swift
myControl.selectedDays = []
```
